fix: CVE fixes, update werkzeug
spec-first/connexion pull request #1967
Opened 2024-08-23 21:02 UTC by mfmarche

Updates werkzeug for CVE-2024-34069

Fixes # .

Changes proposed in this pull request:

 -
 -
 -

2024-08-29 18:28 UTC, chrisinmtown commented
I opened issue https://github.com/spec-first/connexion/issues/1969 for exactly this problem before finding this PR.  Thanks for this! I hope the maintainers review and comment soon.

2024-08-29 18:29 UTC, chrisinmtown commented on tox.ini
>      isort-check
probably should add py311 also, please

2024-08-29 18:30 UTC, chrisinmtown approved these changes
I guess my approval doesn't count for much

2024-08-29 18:34 UTC, chrisinmtown requested changes
A couple tests fail for me under Python3.9, I can send more detail about my env if you like.
```
FAILED tests/api/test_parameters.py::test_cookie_param[swagger.yaml] - TypeError: set_cookie() missing 1 required positional argument: 'server_name'
FAILED tests/api/test_parameters.py::test_cookie_param[openapi.yaml] - TypeError: set_cookie() missing 1 required positional argument: 'server_name'
```

2024-08-30 12:19 UTC, chrisinmtown commented
I cannot comment on the line or file because you didn't touch it in this PR, I recommend bumping the version in `connexion/__init__.py`, maybe:

    __version__ = '2024.0.dev1'

2024-08-30 12:28 UTC, chrisinmtown commented
Here's a test failure. Test environment is macOS with python 3.11, I may need to install Python 3.9 to match your results? Anyhow I don't understand why the `aiohttp_jinja2` module is not found, AFAICT the requires line lists this module just fine.
```
___________________________________ ERROR collecting tests/aiohttp/test_aiohttp_errors.py ___________________________________
ImportError while importing test module '/Users/me/git/github/connexion_mfmarche/tests/aiohttp/test_aiohttp_errors.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
/Users/me/git/github/connexion-mfmarche/tests/aiohttp/test_aiohttp_errors.py:5: in <module>
    ???
connexion/apis/aiohttp_api.py:14: in <module>
    import aiohttp_jinja2
E   ModuleNotFoundError: No module named 'aiohttp_jinja2'
```

2024-08-30 12:37 UTC, mfmarche commented on connexion/apps/flask_app.py
> +import json
ok will move that around.

2024-08-30 16:37 UTC, chrisinmtown commented
Finally realized I had used a hyphen in the cloned directory name and that caused problems, sorry for my confusion. Now `tox` runs without strange messages, shows these failures for Python3.9 tests. I think this is a consequence of upgrading the version of `Werkzeug` now its test Client requires `server_name` as the first argument.

https://tedboy.github.io/flask/generated/generated/werkzeug.Client.set_cookie.html#werkzeug.Client.set_cookie

```
========================================================= FAILURES ==========================================================
______________________________________________ test_cookie_param[swagger.yaml] ______________________________________________

simple_app = <connexion.apps.flask_app.FlaskApp object at 0x113f65d30>

    def test_cookie_param(simple_app):
        app_client = simple_app.app.test_client()
>       app_client.set_cookie(domain="localhost", key="test_cookie", value="hello")
E       TypeError: set_cookie() missing 1 required positional argument: 'server_name'

tests/api/test_parameters.py:526: TypeError
______________________________________________ test_cookie_param[openapi.yaml] ______________________________________________

simple_app = <connexion.apps.flask_app.FlaskApp object at 0x113680a60>

    def test_cookie_param(simple_app):
        app_client = simple_app.app.test_client()
>       app_client.set_cookie(domain="localhost", key="test_cookie", value="hello")
E       TypeError: set_cookie() missing 1 required positional argument: 'server_name'

tests/api/test_parameters.py:526: TypeError
```

2024-08-30 16:46 UTC, chrisinmtown commented on connexion/apps/flask_app.py
> +import json
Cool, this is the position that isort accepted for me:
```
diff --git a/connexion/apps/flask_app.py b/connexion/apps/flask_app.py
index 6a7e61d..ada9c57 100644
--- a/connexion/apps/flask_app.py
+++ b/connexion/apps/flask_app.py
@@ -3,6 +3,7 @@ This module defines a FlaskApp, a Connexion application to wrap a Flask applicat
 """
 
 import datetime
+import json
 import logging
 import pathlib
 from decimal import Decimal
@@ -11,7 +12,6 @@ from types import FunctionType  # NOQA
 import flask
 import werkzeug.exceptions
 from flask import signals
-import json
 
 from ..apis.flask_api import FlaskApi
 from ..exceptions import ProblemException
```

2024-08-30 16:52 UTC, chrisinmtown commented
I solved the `mypy` complaint about a syntax error with this change
```
diff --git a/tests/api/test_responses.py b/tests/api/test_responses.py
index da76bbf..68b9322 100644
--- a/tests/api/test_responses.py
+++ b/tests/api/test_responses.py
@@ -393,29 +393,29 @@ def test_streaming_response(simple_app):
 def test_oneof(simple_openapi_app):
     app_client = simple_openapi_app.app.test_client()
 
-    post_greeting = app_client.post(  # type: flask.Response
+    post_greeting = app_client.post(
         '/v1.0/oneof_greeting',
         data=json.dumps({"name": 3}),
         content_type="application/json"
-    )
+    )  # type: flask.Response
     assert post_greeting.status_code == 200
     assert post_greeting.content_type == 'application/json'
     greeting_reponse = json.loads(post_greeting.data.decode('utf-8', 'replace'))
     assert greeting_reponse['greeting'] == 'Hello 3'
 
-    post_greeting = app_client.post(  # type: flask.Response
+    post_greeting = app_client.post(
         '/v1.0/oneof_greeting',
         data=json.dumps({"name": True}),
         content_type="application/json"
-    )
+    )  # type: flask.Response
     assert post_greeting.status_code == 200
     assert post_greeting.content_type == 'application/json'
     greeting_reponse = json.loads(post_greeting.data.decode('utf-8', 'replace'))
     assert greeting_reponse['greeting'] == 'Hello True'
 
-    post_greeting = app_client.post(  # type: flask.Response
+    post_greeting = app_client.post(
         '/v1.0/oneof_greeting',
         data=json.dumps({"name": "jsantos"}),
         content_type="application/json"
-    )
+    )  # type: flask.Response
     assert post_greeting.status_code == 400
```

2024-08-30 16:57 UTC, chrisinmtown commented
Maybe @Zalando didn't check in quite every file that is needed here, I cannot find `requirements-dev.txt` anywhere:
```
py39-dev: commands[1]> requirements-builder --level=dev --extras aiohttp --req=requirements-devel.txt -o /Users/cl778h/git/github/connexion-spec-first/.tox/requirements-dev.txt setup.py
Usage: requirements-builder [OPTIONS] [SETUP]
Try 'requirements-builder --help' for help.

Error: Invalid value for '--req' / '-r': File 'requirements-devel.txt' does not exist.
```

2024-08-31 12:57 UTC, chrisinmtown commented on setup.py
> +    'werkzeug>=1.0,<4.0',
since werkzeug versions below 3.x have security vulnerabilities, I suggest:

    'werkzeug>=3.0,<4.0',

2024-09-17 13:35 UTC, chrisinmtown commented
@mfmarche I think this PR is exactly on point and will benefit many people including me, do you still have time to push this along?

2024-09-17 13:45 UTC, mfmarche commented
> @mfmarche I think this PR is exactly on point and will benefit many people including me, do you still have time to push this along?

Hi @chrisinmtown, yes have every intention to push along. I will take your comments, thank you for providing those. However, i'm not sure if this will ever get pushed by upstream into the v2 branch? Do you have suggestions how to proceed?

2024-09-17 14:28 UTC, chrisinmtown commented
> Do you have suggestions how to proceed?

Unfortunately for all of us connexion users, I have no suggestions. You might comment on this issue that I wrote, trying to get a reply from the new maintainers: https://github.com/spec-first/connexion/issues/1973

2024-09-28 10:01 UTC, juhoinkinen commented on setup.py
> +    'pytest',
Three lines above the pytest dependency is set to `pytest>=6,<9`, is this unpinned duplicate setting a typo?

2025-04-27 15:20 UTC, donbowman commented
IMHO the best thing for the community would be to accept this PR onto the V2 branch, and publish as a new version on 2.x on connexion existing pypi, allowing those folks who are working on the major rework required for 3.x to work around the *severe* security issues that are  currently pinned to v2.

Failing that, the next best alternative is to create a hard fork and keep it on the v2 compatibility, publish that to pypi as an alternate name. In which case we would need at least 2 maintainers who are independent of each other.

It would be nice to get some guidance from the maintainers as to which direction you prefer. If you are against the idea of updating the current v2 branch dependencies, then we can proceed with the hard fork. If its just a resourcing issue, is there something one of us can do to assist?

I believe @mfmarche has done the work on the PR, so it really comes down to this question.

2025-05-01 12:44 UTC, chrisinmtown commented
> It would be nice to get some guidance from the maintainers as to which direction you prefer.

Does anyone know how to contact @RobbeSneyders and @Ruwann directly to see if they're doing OK, still working in software, still interested in being maintainers of this little project? If they have decided they no longer want to be involved, that would be useful information.

2025-05-01 12:47 UTC, chrisinmtown commented
> __version__ = '2024.0.dev1'

@mfmarche would you please bump the version string? Can't just reuse the old one. 

Also are you considering adding modern Pythons like 3.11, 3.12 to the tox config?

2025-05-01 13:15 UTC, chrisinmtown commented
@mfmarche  I'll try to keep up :)

2025-05-05 20:02 UTC, chrisinmtown commented
@mfmarche I don't mean to nag you, but you said you were closing this PR, yet it remains open?

@donbowman you might want to move your comment to PR #1992 ?

2025-05-05 20:06 UTC, closed without merging